import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const seen=new Map(),chunks=[];
function bundle(file){
 file=path.resolve(file);if(seen.has(file))return seen.get(file);
 const id='m'+seen.size;seen.set(file,id);let code=fs.readFileSync(file,'utf8');
 code=code.replace(/import\s*\{([^}]+)\}\s*from\s*['"]([^'"]+)['"];?/g,(_,names,source)=>{
 if(!source.startsWith('.'))throw new Error('Use dynamic import for external SDK: '+source);
 const dep=bundle(path.resolve(path.dirname(file),source));return `const {${names.replace(/\s+as\s+/g,':')}}=${dep};`;
 });
 const exports=[];
 code=code.replace(/export\s*\{([^}]+)\}\s*from\s*['"]([^'"]+)['"];?/g,(_,names,source)=>{const dep=bundle(path.resolve(path.dirname(file),source));for(const name of names.split(','))exports.push(name.trim());return `const {${names}}=${dep};`;});
 code=code.replace(/export\s+(async\s+)?(function|class|const|let|var)\s+(\w+)/g,(_,a='',kind,name)=>{exports.push(name);return `${a}${kind} ${name}`});
 code=code.replace(/export\s*\{([^}]+)\};?/g,(_,list)=>{for(const name of list.split(',')){if(name.includes(' as '))throw new Error('export alias not supported');exports.push(name.trim())}return ''});
 if(/\bexport\s/.test(code))throw new Error('Unsupported export '+file);
 chunks.push(`const ${id}=await(async()=>{\n${code}\nreturn {${exports.join(',')}};\n})();`);return id;
}
bundle(path.join(root,'src/app.mjs'));
let html=fs.readFileSync(path.join(root,'index.html'),'utf8');
html=html.replace(/<link[^>]+href=["'](?:\.\/)?assets\/styles\.css["'][^>]*>/,()=>'<style>'+fs.readFileSync(path.join(root,'assets/styles.css'),'utf8')+'</style>');
html=html.replace(/<script[^>]+src=["'](?:\.\/)?src\/app\.mjs["'][^>]*><\/script>/,()=>'<script>\n(async()=>{\n'+chunks.join('\n')+'\n})();\n</script>');
html=html.replace('<script src="firebase-config.js"></script>','<script>window.MADAF_FIREBASE_CONFIG=null;</script>');
if(html.includes('src/app.mjs'))throw new Error('App script replacement failed');
fs.mkdirSync(path.join(root,'dist'),{recursive:true});fs.writeFileSync(path.join(root,'dist/Madaf_V2_Preview.html'),html);
console.log('Built standalone HTML:',Buffer.byteLength(html),'bytes');

// The app is served under /app/; public/index.html is the separate public landing screen.
const publicDir=path.join(root,'public/app');fs.rmSync(publicDir,{recursive:true,force:true});fs.mkdirSync(publicDir,{recursive:true});fs.copyFileSync(path.join(root,'index.html'),path.join(publicDir,'index.html'));
fs.writeFileSync(path.join(publicDir,'firebase-config.js'),"// Generated by scripts/build.mjs: config is read from Firebase Hosting's /__/firebase/init.json.\nwindow.MADAF_FIREBASE_CONFIG='hosting';\n");for(const name of ['src','assets'])fs.cpSync(path.join(root,name),path.join(publicDir,name),{recursive:true});
