import {makeSeed} from './seed.mjs';
export class DomainError extends Error { constructor(code,message){super(message);this.name='DomainError';this.code=code;} }
const fail=(code,message)=>{throw new DomainError(code,message);};
const check=(condition,code,message)=>{if(!condition)fail(code,message);};
const integer=(n,min=0)=>Number.isSafeInteger(n)&&n>=min;
const text=(v,max=200)=>typeof v==='string'&&v.trim().length>0&&v.length<=max;
const stable=v=>v&&typeof v==='object'?Array.isArray(v)?v.map(stable):Object.fromEntries(Object.keys(v).sort().map(k=>[k,stable(v[k])])):v;
const skuKey=s=>s.normalize('NFKC').toUpperCase().replace(/[\s\-‐‑–—]/g,'');
const open=r=>r&&['pending','stock_conflict'].includes(r.status);
export function execute(input,cmd,actor){
 check(cmd&&text(cmd.key,160),'KEY_REQUIRED','חסר מזהה פעולה');check(actor&&text(actor.id,160),'AUTH_REQUIRED','יש להתחבר');
 const member=input.users.find(u=>u.id===actor.id);
 check(member&&member.active!==false&&member.role===actor.role,'FORBIDDEN','אין הרשאה לפעולה');
 const signature=JSON.stringify(stable({cmd,actor:{id:actor.id,role:actor.role}}));
 const receiptKey=`${actor.id}:${cmd.key}`;
 if(Object.hasOwn(input.receipts,receiptKey)){check(input.receipts[receiptKey].signature===signature,'KEY_REUSED','מזהה הפעולה כבר בשימוש');return structuredClone(input);}
 check(member.role==='admin'||(member.businessId||null)===(actor.businessId||null),'FORBIDDEN','אין הרשאה לעסק');
 const s=structuredClone(input),now=new Date().toISOString();s.auditEvents??=[];
 const id=prefix=>`${prefix}_${globalThis.crypto.randomUUID()}`;
 const admin=()=>check(member.role==='admin','FORBIDDEN','פעולה למנהל בלבד');
 const business=(bid=member.businessId)=>{const b=s.businesses.find(b=>b.id===bid);check(b,'BUSINESS_REQUIRED','יש להשלים פרטי עסק');return b;};
 const own=b=>check(member.role==='admin'||member.businessId===b.id,'FORBIDDEN','אין גישה לעסק');
 const product=pid=>{const p=s.products.find(p=>p.id===pid);check(p,'PRODUCT_MISSING','מוצר לא נמצא');return p;};
 const audit=(type,data)=>s.auditEvents.push({id:id('audit'),type,actorId:actor.id,at:now,...data});
 const emit=(o,type)=>{o.events.push({id:id('evt'),type,actorId:actor.id,at:now,version:o.version});s.notifications.push({id:id('notification'),eventType:type,orderId:o.id,businessId:o.businessId,channel:'outbox',provider:null,status:'queued',attempts:0,createdAt:now,lastError:null,targets:type==='order_created'?['business','operations',...(o.status==='pending_approval'?['admin']:[])]:type.endsWith('_requested')?['admin']:['business'],snapshot:{number:o.number,status:o.status,business:o.businessSnapshot,items:o.items,subtotal:o.subtotal,vat:o.vat,total:o.total,note:o.note}});};
 const inv=(pid,delta,reason,orderId=null)=>{const p=product(pid),before=p.stock;check(integer(before+delta),'STOCK_CONFLICT','המלאי אינו מספיק');p.stock+=delta;s.inventoryEvents.push({id:id('inv'),productId:pid,before,delta,after:p.stock,reason,orderId,actorId:actor.id,at:now});};
 const lines=(items,original=[],allowDisabled=false)=>{check(Array.isArray(items)&&items.length>0&&items.length<=500,'INVALID_ITEMS','יש לבחור מוצרים');const seen=new Set();return items.map(i=>{check(i&&integer(i.quantity,1)&&i.quantity<=100000,'INVALID_QUANTITY','יש להזין מספר ארגזים שלם וחיובי');check(!seen.has(i.productId),'DUPLICATE_ITEM','מוצר מופיע פעמיים');seen.add(i.productId);const p=product(i.productId),old=original.find(x=>x.productId===p.id),cat=s.categories.find(c=>c.id===p.categoryId);check((p.active&&cat?.active)||(allowDisabled&&old&&i.quantity<=old.quantity),'PRODUCT_INACTIVE','המוצר אינו זמין להזמנה');return {productId:p.id,sku:old?.sku??p.sku,name:old?.name??p.name,quantity:i.quantity,price:old?.price??p.price,unitsPerCase:old?.unitsPerCase??p.unitsPerCase};});};
 const amounts=(items,rate)=>{const subtotal=items.reduce((sum,i)=>sum+i.quantity*i.price,0);check(integer(subtotal),'INVALID_AMOUNT','סכום לא תקין');check(subtotal>=s.settings.minimumOrder,'MINIMUM_ORDER','ההזמנה מתחת למינימום');const vat=Math.round(subtotal*rate);return {subtotal,vatRate:rate,vat,total:subtotal+vat};};
 const stockDelta=(oldItems,newItems,reason,oid)=>{const ids=new Set([...oldItems,...newItems].map(i=>i.productId));const ds=[...ids].map(pid=>[pid,(oldItems.find(i=>i.productId===pid)?.quantity||0)-(newItems.find(i=>i.productId===pid)?.quantity||0)]);if(ds.some(([pid,d])=>product(pid).stock+d<0))return false;for(const [pid,d]of ds)if(d)inv(pid,d,reason,oid);return true;};
 const order=()=>{const o=s.orders.find(o=>o.id===cmd.orderId);check(o,'ORDER_MISSING','הזמנה לא נמצאה');own(business(o.businessId));check(cmd.version===o.version,'STALE_VERSION','ההזמנה עודכנה, יש לרענן');return o;};
 const touch=o=>{o.version++;o.updatedAt=now;};
 const validateBusiness=b=>{for(const f of ['name','contactName','phone','address','taxId'])check(text(b[f],f==='address'?500:160),'INVALID_PROFILE','יש להשלים את פרטי העסק');};
 switch(cmd.type){
 case 'onboard':{check(member.role==='customer'&&!member.businessId,'ALREADY_ONBOARDED','כבר קיים עסק לחשבון');const b={id:id('biz'),...Object.fromEntries(['name','contactName','phone','address','taxId'].map(k=>[k,cmd.business?.[k]?.trim()])),approved:false,active:true};validateBusiness(b);s.businesses.push(b);s.users.find(u=>u.id===member.id).businessId=b.id;audit('business_created',{businessId:b.id});break;}
 case 'updateBusiness':{const b=business(cmd.businessId);own(b);const patch=cmd.patch||{};check(Object.keys(patch).every(k=>['name','contactName','phone','address','taxId'].includes(k)),'INVALID_FIELDS','שדות לא מותרים');if(member.role!=='admin'&&s.orders.some(o=>o.businessId===b.id))check(!['name','taxId'].some(k=>k in patch&&patch[k]!==b[k]),'IDENTITY_LOCKED','שינוי זהות העסק דורש מנהל');const before=structuredClone(b);Object.assign(b,patch);validateBusiness(b);audit('business_updated',{businessId:b.id,before,after:b});break;}
 case 'submitOrder':{check(member.role==='customer','FORBIDDEN','הזמנה נשלחת מחשבון לקוח');const b=business();check(b.active,'BUSINESS_INACTIVE','העסק מושבת');const items=lines(cmd.items);for(const i of items)check(cmd.expectedPrices?.[i.productId]===i.price,'PRICE_CHANGED','מחיר מוצר השתנה, יש לאשר מחדש');check(typeof(cmd.note??'')==='string'&&(cmd.note??'').length<=2000,'INVALID_NOTE','הערה ארוכה מדי');const oid=id('order'),o={id:oid,number:`M-${s.nextOrder++}`,businessId:b.id,businessSnapshot:structuredClone(b),status:b.approved?'received':'pending_approval',items,...amounts(items,s.settings.vatRate),note:cmd.note||'',version:1,createdAt:now,updatedAt:now,request:null,requestHistory:[],events:[]};check(stockDelta([],items,'order_submitted',oid),'STOCK_CONFLICT','המלאי השתנה');s.orders.push(o);emit(o,'order_created');break;}
 case 'requestChange':case 'requestCancel':{check(member.role==='customer','FORBIDDEN','בקשה מיועדת ללקוח');const o=order();check(o.status==='received','INVALID_STATE','ניתן לבקש שינוי רק להזמנה שהתקבלה');check(!open(o.request),'REQUEST_OPEN','כבר קיימת בקשה פתוחה');const r={id:id('request'),type:cmd.type==='requestChange'?'change':'cancel',status:'pending',createdAt:now,actorId:actor.id};if(r.type==='change'){r.items=lines(cmd.items,o.items,true);amounts(r.items,o.vatRate);}o.request=r;touch(o);emit(o,`${r.type}_requested`);break;}
 case 'resolveRequest':{admin();const o=order();check(o.status==='received'&&open(o.request),'INVALID_STATE','אין בקשה פעילה שניתן להכריע');check(typeof cmd.approve==='boolean','INVALID_DECISION','חסרה החלטה');const r=o.request;if(cmd.approve&&r.type==='change'){const proposed=lines(cmd.items||r.items,o.items,true);for(const item of proposed){const snapshot=r.items?.find(x=>x.productId===item.productId);if(snapshot)item.price=snapshot.price;}const totals=amounts(proposed,o.vatRate);if(!stockDelta(o.items,proposed,'change_approved',o.id)){r.items=proposed;r.status='stock_conflict';touch(o);emit(o,'change_stock_conflict');break;}r.items=proposed;r.beforeItems=structuredClone(o.items);o.items=proposed;Object.assign(o,totals);}if(cmd.approve&&r.type==='cancel'){check(stockDelta(o.items,[],'order_cancelled',o.id),'STOCK_CONFLICT','שגיאת מלאי');o.status='cancelled';}r.status=cmd.approve?'approved':'rejected';r.resolvedAt=now;r.resolvedBy=actor.id;o.requestHistory.push(structuredClone(r));o.request=null;touch(o);emit(o,`${r.type}_${r.status}`);break;}
 case 'approveOrder':case 'rejectOrder':{admin();const o=order();check(o.status==='pending_approval','INVALID_STATE','ההזמנה אינה ממתינה לאישור');if(cmd.type==='rejectOrder'){check(stockDelta(o.items,[],'order_rejected',o.id),'STOCK_CONFLICT','שגיאת מלאי');o.status='rejected';}else{if(cmd.items){const items=lines(cmd.items,o.items,true),totals=amounts(items,o.vatRate);check(stockDelta(o.items,items,'admin_initial_edit',o.id),'STOCK_CONFLICT','אין מספיק מלאי');audit('initial_order_edit',{orderId:o.id,before:o.items,after:items});o.items=items;Object.assign(o,totals);}business(o.businessId).approved=true;o.status='received';}touch(o);emit(o,cmd.type==='approveOrder'?'order_approved':'order_rejected');break;}
 case 'advanceOrder':{admin();const o=order();check(['received','picking'].includes(o.status),'INVALID_STATE','מעבר סטטוס לא חוקי');check(!open(o.request),'REQUEST_OPEN','יש להכריע בבקשה תחילה');o.status=o.status==='received'?'picking':'completed';touch(o);emit(o,`order_${o.status}`);break;}
 case 'adjustInventory':{admin();check(Number.isSafeInteger(cmd.delta)&&cmd.delta!==0&&text(cmd.reason,500),'INVALID_ADJUSTMENT','נדרשים תיקון שלם וסיבה');inv(cmd.productId,cmd.delta,cmd.reason);break;}
 case 'saveProduct':{admin();const p=cmd.product||{},existing=p.id?s.products.find(x=>x.id===p.id):null;check(!p.id||existing,'PRODUCT_MISSING','מוצר לא נמצא');check(text(p.name)&&text(p.sku,80)&&text(p.description,5000)&&text(p.image,1500000)&&/^(https?:\/\/|data:image\/(?:png|jpeg|webp|gif|svg\+xml)[;,])/i.test(p.image)&&integer(p.price,1)&&integer(p.unitsPerCase,1)&&typeof p.active==='boolean','INVALID_PRODUCT','יש להשלים פרטי מוצר תקינים');check(!s.products.some(x=>x.id!==p.id&&skuKey(x.sku)===skuKey(p.sku)),'SKU_DUPLICATE','המק״ט כבר קיים');const cat=s.categories.find(c=>c.id===p.categoryId);check(cat&&(cat.active||existing?.categoryId===cat.id),'CATEGORY_INACTIVE','קטגוריה אינה זמינה');check(!existing||p.stock===undefined||p.stock===existing.stock,'STOCK_PATH','תיקון מלאי מתבצע במסלול ייעודי');const clean={sku:p.sku.trim(),name:p.name.trim(),description:String(p.description||'').slice(0,5000),categoryId:p.categoryId,unitsPerCase:p.unitsPerCase,price:p.price,active:p.active,image:String(p.image||'')};check(clean.image.length<=1500000,'IMAGE_TOO_LARGE','התמונה גדולה מדי');if(existing){Object.assign(existing,clean);audit('product_updated',{productId:existing.id});}else{check(integer(p.stock??0),'INVALID_STOCK','מלאי פתיחה לא תקין');const fresh={id:id('p'),...clean,stock:0};s.products.push(fresh);inv(fresh.id,p.stock??0,'opening_stock');audit('product_created',{productId:fresh.id});}break;}
 case 'saveCategory':{admin();const c=cmd.category||{},existing=c.id?s.categories.find(x=>x.id===c.id):null;check(!c.id||existing,'CATEGORY_MISSING','קטגוריה לא נמצאה');check(text(c.name,100)&&typeof c.active==='boolean','INVALID_CATEGORY','קטגוריה לא תקינה');const value={name:c.name.trim(),active:c.active,sortOrder:Number.isFinite(c.sortOrder)?c.sortOrder:0};if(existing)Object.assign(existing,value);else s.categories.push({id:id('cat'),...value});audit('category_saved',{categoryId:existing?.id||s.categories.at(-1).id});break;}
 case 'deleteCategory':{admin();check(s.categories.some(c=>c.id===cmd.categoryId),'CATEGORY_MISSING','קטגוריה לא נמצאה');check(!s.products.some(p=>p.categoryId===cmd.categoryId),'CATEGORY_IN_USE','קטגוריה משויכת למוצרים; ניתן להשבית אותה');s.categories=s.categories.filter(c=>c.id!==cmd.categoryId);audit('category_deleted',{categoryId:cmd.categoryId});break;}
 case 'saveSettings':{admin();const v=cmd.settings;check(v&&integer(v.minimumOrder)&&Number.isFinite(v.vatRate)&&v.vatRate>=0&&v.vatRate<=1,'INVALID_SETTINGS','הגדרות לא תקינות');s.settings={minimumOrder:v.minimumOrder,vatRate:v.vatRate};audit('settings_updated',{settings:s.settings});break;}
 case 'setBusinessActive':{admin();check(typeof cmd.active==='boolean','INVALID_BUSINESS','מצב עסק לא תקין');business(cmd.businessId).active=cmd.active;audit('business_active',{businessId:cmd.businessId,active:cmd.active});break;}
 default:fail('UNKNOWN_COMMAND','פעולה אינה מוכרת');
 }
 s.revision++;s.receipts[receiptKey]={signature,revision:s.revision,createdAt:now};return s;
}
export function seed(){return makeSeed(execute);}
