const picture=(color,index)=>'data:image/svg+xml;charset=utf-8,'+encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="480" height="400" viewBox="0 0 480 400"><defs><linearGradient id="b" x2="0" y2="1"><stop stop-color="#f5f0e8"/><stop offset="1" stop-color="#e7dfd2"/></linearGradient><pattern id="p" width="16" height="16" patternUnits="userSpaceOnUse"><path d="M0 1h16M1 0v16" stroke="#fff" stroke-opacity=".12"/></pattern><filter id="s"><feDropShadow dx="0" dy="12" stdDeviation="9" flood-opacity=".15"/></filter></defs><rect width="480" height="400" fill="url(#b)"/><ellipse cx="245" cy="332" rx="155" ry="16" fill="#b4a38d" opacity=".18"/><g filter="url(#s)" transform="rotate(${index%2?'-7':'5'} 240 200)"><rect x="115" y="80" width="245" height="238" rx="${index%3===0?55:9}" fill="${color}"/><rect x="115" y="80" width="245" height="238" rx="9" fill="url(#p)"/><path d="M145 88v220M330 88v220" stroke="#fff" stroke-opacity=".35" stroke-width="3"/><path d="M125 288h225" stroke="#fff" stroke-opacity=".3" stroke-width="2"/><rect x="205" y="255" width="64" height="25" rx="3" fill="#eee6d6"/><text x="237" y="272" font-family="serif" font-size="13" text-anchor="middle" fill="#5b554b">MADAF</text></g></svg>`);
export function makeSeed(execute){
 const colors=['#b87860','#8b9479','#cfb28f','#737f86','#bd9989','#b7ac91','#6c7770','#a18a7d'];
 const names=['צעיף פשתן חמרה','צעיף כותנה זית','צעיף ארוג חול','צעיף ערב כחול','צעיף רך ורדרד','צעיף קיץ אבן','צעיף חורף יער','צעיף קלאסי מוקה','מגבת אורחים פשתן','כיסוי כרית זית','מפת שולחן טבעית','מגבת מטבח כחולה','מפיות בד ורודות','ראנר שולחן חול','שמיכת כותנה יער','כיסוי כרית מוקה','תיק בד חמרה','נרתיק בד זית','שקית מתנה טבעית','תיק צד כחול','נרתיק רחצה ורוד','תיק קניות אבן','ארנק בד יער','סט שקיות מוקה'];
 let s={schemaVersion:2,revision:0,settings:{minimumOrder:150000,vatRate:.18},businesses:[{id:'biz_demo',name:'סטודיו נווה',contactName:'נועה לוי',phone:'0501234567',address:'רחוב הגפן 12, תל אביב',taxId:'512345678',approved:true,active:true},{id:'biz_other',name:'בית החומר',contactName:'אורי כהן',phone:'0527654321',address:'הרצל 24, חיפה',taxId:'512345679',approved:true,active:true},{id:'biz_new',name:'פינה טובה',contactName:'מיה ישראלי',phone:'0541239876',address:'העצמאות 8, רחובות',taxId:'512345680',approved:false,active:true}],users:[{id:'admin',role:'admin',name:'מנהל מדף',businessId:null},{id:'customer_demo',role:'customer',businessId:'biz_demo',name:'נועה'},{id:'customer_other',role:'customer',businessId:'biz_other',name:'אורי'},{id:'customer_new',role:'customer',businessId:'biz_new',name:'מיה'}],categories:[{id:'scarves',name:'צעיפים וטקסטיל',active:true,sortOrder:1},{id:'home',name:'לבית ולשולחן',active:true,sortOrder:2},{id:'accessories',name:'תיקים ואביזרים',active:true,sortOrder:3}],products:names.map((name,i)=>({id:`p${i+1}`,sku:`MD-${String(i+1).padStart(3,'0')}`,name,description:'מרקם טבעי, גימור מוקפד וגוון שמתאים לכל קולקציה. אריזה סיטונאית מסודרת, מוכנה למדף שלכם.',categoryId:['scarves','home','accessories'][Math.floor(i/8)],unitsPerCase:i%3===0?12:24,price:[18000,24000,32000,42000][i%4],stock:30+i,active:true,image:picture(colors[i%8],i)})),orders:[],inventoryEvents:[],notifications:[],auditEvents:[],receipts:{},nextOrder:1001};
 const initial='2026-10-01T08:00:00.000Z';s.inventoryEvents=s.products.map(p=>({id:`opening_${p.id}`,productId:p.id,before:0,delta:p.stock,after:p.stock,reason:'opening_stock',orderId:null,actorId:'admin',at:initial}));
 const admin={id:'admin',role:'admin'},customer=id=>({...s.users.find(u=>u.id===id)});let seq=0;
 const run=(type,actor,payload)=>s=execute(s,{type,key:`seed_${++seq}`,...payload},actor);
 const submit=(uid,items,note)=>{run('submitOrder',customer(uid),{items,expectedPrices:Object.fromEntries(s.products.map(p=>[p.id,p.price])),note});return s.orders.at(-1).id;};
 let oid=submit('customer_demo',[{productId:'p1',quantity:5},{productId:'p2',quantity:4}],'נא לארוז בנפרד לפי סוג');
 run('advanceOrder',admin,{orderId:oid,version:1});run('advanceOrder',admin,{orderId:oid,version:2});
 oid=submit('customer_demo',[{productId:'p1',quantity:4},{productId:'p9',quantity:5}],'');
 run('requestChange',customer('customer_demo'),{orderId:oid,version:1,items:[{productId:'p1',quantity:5},{productId:'p9',quantity:5}]});
 submit('customer_new',[{productId:'p17',quantity:5},{productId:'p18',quantity:3}],'זו ההזמנה הראשונה שלנו, תודה!');
 oid=submit('customer_other',[{productId:'p11',quantity:5},{productId:'p12',quantity:2}],'');
 run('requestCancel',customer('customer_other'),{orderId:oid,version:1});
 oid=submit('customer_other',[{productId:'p6',quantity:8}],'');run('advanceOrder',admin,{orderId:oid,version:1});
 // Low-stock and exhausted products remain traceable through the same ledger.
 run('adjustInventory',admin,{productId:'p5',delta:2-s.products.find(p=>p.id==='p5').stock,reason:'נתוני הדגמה — יתרה נמוכה'});
 run('adjustInventory',admin,{productId:'p24',delta:-s.products.find(p=>p.id==='p24').stock,reason:'נתוני הדגמה — המלאי אזל'});
 return s;
}
