const {chromium}=require('playwright');const http=require('http'),fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),out=path.join(root,'qa');fs.mkdirSync(out,{recursive:true});
const server=http.createServer((req,res)=>{let pathname=decodeURIComponent(req.url.split('?')[0]);const file=path.resolve(root,'.'+(pathname==='/'?'/index.html':pathname));if(!file.startsWith(root+path.sep)){res.statusCode=403;return res.end()}try{res.setHeader('Content-Type',(file.endsWith('.mjs')||file.endsWith('.js'))?'text/javascript':file.endsWith('.css')?'text/css':file.endsWith('.svg')?'image/svg+xml':'text/html');res.end(fs.readFileSync(file))}catch{res.statusCode=404;res.end()}});
const results=[],errors=[];let browser;
async function test(name,fn){try{await fn();results.push({name,status:'PASS'});console.log('PASS',name)}catch(e){results.push({name,status:'FAIL',error:e.message});console.log('FAIL',name,e.message)}}
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;const executablePath=process.env.MADAF_CHROMIUM;browser=await chromium.launch({...(executablePath?{executablePath}:{}),args:['--no-sandbox','--disable-gpu','--disable-software-rasterizer','--no-zygote'],headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000}});const p=await context.newPage();p.setDefaultTimeout(7000);p.on('pageerror',e=>errors.push(e.message));const click=sel=>p.locator(sel).first().click();
await test('desktop customer loads without errors',async()=>{await p.goto(base);await click('[data-persona="customer"]');await p.locator('.product').first().waitFor();assert.ok(await p.locator('.product').count()>15);await p.screenshot({path:path.join(out,'customer-desktop.png'),fullPage:true})});
await test('normalized SKU search and clear',async()=>{await p.locator('#search').fill('MD001');assert.equal(await p.locator('.product').count(),1);await click('[data-action="clear-search"]')});
await test('quantity + direct entry and cart expansion',async()=>{await p.locator('[data-quantity="p1"][data-prefix^="card"]').first().fill('10');await p.locator('[data-quantity="p1"][data-prefix^="card"]').first().press('Tab');await click('[data-action="expand"]');assert.equal(await p.locator('.living.expanded').count(),1);assert.ok((await p.locator('.living').innerText()).includes('10 ארגזים'))});
await test('quick view Escape restores focus',async()=>{await click('[data-action="quick"][data-id="p3"]');assert.equal(await p.locator('[role="dialog"]').count(),1);await p.keyboard.press('Escape');assert.equal(await p.locator('[role="dialog"]').count(),0)});
await test('checkout submits and clears draft',async()=>{await click('[data-action="checkout"]');await click('#checkout-form button');await p.locator('#checkout-form').waitFor({state:'detached'});assert.ok((await p.locator('h1').innerText()).includes('ההזמנות שלי'));const state=await p.evaluate(()=>JSON.parse(localStorage.getItem('madaf-v2-state')));assert.equal(state.orders.at(-1).status,'received');assert.equal(state.orders.at(-1).items[0].quantity,10)});
await test('customer detail includes snapshot timeline and requests',async()=>{await click('[data-action="order"]');assert.equal(await p.locator('.order-lines').count(),1);assert.ok(await p.locator('[data-action="cancel"]').count());await p.keyboard.press('Escape')});
async function logout(){await click('[data-action="drawer"][data-side="nav"]');await click('[data-action="logout"]')}
await test('admin Inbox and creation form open',async()=>{await logout();await click('[data-persona="admin"]');await click('[data-action="view"][data-view="products"]');await click('[data-action="new-product"]');assert.equal(await p.locator('#product-form').count(),1);await p.keyboard.press('Escape');await click('[data-action="view"][data-view="categories"]');await click('[data-action="new-category"]');await p.locator('#category-form input[name="name"]').fill('בדיקת קטגוריה');await click('#category-form button');await p.locator('#category-form').waitFor({state:'detached'});assert.ok((await p.locator('.queue').innerText()).includes('בדיקת קטגוריה'))});
await test('inventory adjustment and audit',async()=>{await click('[data-action="view"][data-view="inventory"]');await click('[data-action="select-product"][data-id="p2"]');await click('[data-action="adjust"]');await p.locator('[name="delta"]').fill('2');await p.locator('[name="reason"]').fill('בדיקת ספירה');await click('#inventory-form button');await p.locator('#inventory-form').waitFor({state:'detached'});assert.ok((await p.locator('.ledger').innerText()).includes('בדיקת ספירה'))});
await test('admin desktop screenshot',async()=>{await click('[data-action="view"][data-view="inbox"]');await click('[data-action="order"]');await p.screenshot({path:path.join(out,'admin-desktop.png'),fullPage:true})});
await test('new business isolation onboarding',async()=>{await logout();await click('[data-persona="new"]');for(const[k,v]of Object.entries({name:'חנות עצמאית',taxId:'123456789',contactName:'דנה',phone:'0501234567',address:'רחוב בדיקה 1'}))await p.locator('#business-form [name="'+k+'"]').fill(v);await click('#business-form button');await p.locator('.product').first().waitFor();await click('[data-action="view"][data-view="orders"]');assert.equal(await p.locator('.queue-item').count(),0)});
const mobile=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const m=await mobile.newPage();m.on('pageerror',e=>errors.push(e.message));
await test('mobile catalog and rail context',async()=>{await m.goto(base);await m.locator('[data-persona="customer"]').click();await m.locator('.rail').last().evaluate(e=>e.scrollLeft=-220);const before=await m.locator('.rail').last().evaluate(e=>e.scrollLeft);await m.locator('[data-action="qty"][data-id="p1"][data-delta="1"]').first().click();const after=await m.locator('.rail').last().evaluate(e=>e.scrollLeft);assert.ok(Math.abs(before-after)<2);await m.screenshot({path:path.join(out,'customer-mobile.png'),fullPage:true});assert.ok(await m.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1))});
await test('mobile living cart open and note persists',async()=>{await m.locator('[data-action="expand"]').click();await m.locator('#cart-note').fill('הערה שנשמרת');await m.reload();await m.locator('[data-action="expand"]').click();assert.equal(await m.locator('#cart-note').inputValue(),'הערה שנשמרת');await m.screenshot({path:path.join(out,'cart-mobile.png')})});
await test('standalone file opens and operates',async()=>{const f=await browser.newPage();f.on('pageerror',e=>errors.push(e.message));await f.goto('file://'+path.join(root,'dist/Madaf_V2_Preview.html'));await f.locator('[data-persona="customer"]').click();await f.locator('[data-action="qty"][data-id="p1"][data-delta="1"]').first().click();assert.ok((await f.locator('.living').innerText()).includes('1 ארגזים'));await f.close()});
await test('no uncaught JavaScript exceptions',async()=>assert.deepEqual(errors,[]));
fs.writeFileSync(path.join(out,'browser-results.json'),JSON.stringify({testedAt:new Date().toISOString(),engine:await browser.version(),results,errors},null,2));await browser.close();server.close();if(results.some(r=>r.status==='FAIL'))process.exitCode=1;
})().catch(e=>{console.error(e);browser?.close();server.close();process.exitCode=1});
