import test from 'node:test';import assert from 'node:assert/strict';import {createDemoRepository} from '../src/repository.mjs';
class Storage{data=new Map();fail=false;getItem(k){return this.data.get(k)||null;}setItem(k,v){if(this.fail)throw Error('quota');this.data.set(k,v);}removeItem(k){this.data.delete(k);}}
let pending=Promise.resolve();function setup({locks=true}={}){globalThis.localStorage=new Storage();globalThis.sessionStorage=new Storage();globalThis.addEventListener=()=>{};pending=Promise.resolve();Object.defineProperty(globalThis,'navigator',{configurable:true,value:locks?{locks:{request(_name,fn){const p=pending.then(fn);pending=p.catch(()=>{});return p;}}}:{}});}
const orderCommand=(repo,key='order')=>({type:'submitOrder',key,items:[{productId:'p1',quantity:10}],expectedPrices:{p1:repo.snapshot().products[0].price}});
test('demo onboard creates new business and retry keeps identity',async()=>{setup();const r=await createDemoRepository();await r.signIn('new');const c={type:'onboard',key:'onboard',business:{name:'חדש',contactName:'שם',phone:'0501234567',address:'כתובת',taxId:'999'}};await r.command(c);const id=r.actor.businessId;assert.ok(id);await r.command(c);assert.equal(r.actor.businessId,id);assert.equal(r.snapshot().businesses.length,4);});
test('quota failure commits neither memory nor storage',async()=>{setup();const r=await createDemoRepository();await r.signIn('customer');const before=r.snapshot();localStorage.fail=true;await assert.rejects(r.command(orderCommand(r)),/לא ניתן לשמור/);assert.deepEqual(r.snapshot(),before);localStorage.fail=false;await r.command(orderCommand(r));assert.equal(r.snapshot().orders.length,before.orders.length+1);});
test('two repository instances serialize competing stock mutations',async()=>{setup();const a=await createDemoRepository(),b=await createDemoRepository();await a.signIn('customer');await b.signIn('customer');const before=a.snapshot().products[0].stock;const c={...orderCommand(a),items:[{productId:'p1',quantity:before}]};const results=await Promise.allSettled([a.command({...c,key:'a'}),b.command({...c,key:'b'})]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal(results.filter(r=>r.status==='rejected').length,1);});
test('without locks demo state is isolated and does not overwrite durable storage',async()=>{setup({locks:false});const a=await createDemoRepository(),b=await createDemoRepository();await a.signIn('customer');const n=b.snapshot().orders.length;await a.command(orderCommand(a));assert.equal(b.snapshot().orders.length,n);assert.equal(localStorage.data.size,0);assert.equal(a.persistence,'session');});
test('queued command cannot run under replacement session identity',async()=>{setup();const r=await createDemoRepository();await r.signIn('admin');let release;pending=new Promise(resolve=>release=resolve);const before=r.snapshot().settings.minimumOrder;const promise=r.command({type:'saveSettings',key:'queued',settings:{minimumOrder:123,vatRate:.18}});await r.signOut();release();await assert.rejects(promise);assert.equal(r.snapshot().settings.minimumOrder,before);});
test('signed-out commands and customer image uploads denied',async()=>{setup();const r=await createDemoRepository();await assert.rejects(r.command({type:'saveSettings',key:'no'}));await r.signIn('customer');await assert.rejects(r.uploadImage({type:'image/png',size:10}));});
test('queued customer submission must not move to another business on session switch',async()=>{setup();const r=await createDemoRepository();await r.signIn('customer');let release;pending=new Promise(resolve=>release=resolve);const n=r.snapshot().orders.length;const promise=r.command(orderCommand(r,'switch'));await r.signIn('customer','biz_other');release();await assert.rejects(promise);assert.equal(r.snapshot().orders.length,n);});
